Repository WaifuAPI/Waifu.it, pull requests merged in 2022-10, with the labels that each got.

#37 Updated packages
  package-lock.json
Labels: enhancement, hacktoberfest-accepted

#36 Updated CONTRIBUTING.md to add a "create token" step
  CONTRIBUTING.md
Labels: documentation

#38 Staging
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted
